# It contains the default values for training a FastConformer-Hybrid-Transducer-CTC ASR model, large size (~115M) with sub-word encoding.
# The model would have two decoders: RNNT (Transducer) and CTC
#
# FastConformer: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/models.html#fast-conformer
# Hybrid ASR: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/models.html#hybrid-transducer-ctc
#
name: "FastConformer-Hybrid-TDT-CTC-BPE"

model:
  sample_rate: 16000

  compute_eval_loss: false # eval samples can be very long and exhaust memory.
  # Disable computation of transducer loss during validation/testing with this flag.
  log_prediction: true
  skip_nan_grad: false

  model_defaults:
    enc_hidden: ${model.encoder.d_model}
    pred_hidden: 640
    joint_hidden: 640
    tdt_durations: [0, 1, 2, 3, 4]
    num_tdt_durations: 5

  train_ds:
    manifest_filepath: ./output/train_manifest.jsonl
    sample_rate: ${model.sample_rate}
    batch_size: 32 # you may increase batch_size if your memory allows
    shuffle: true
    num_workers: 8
    pin_memory: true
    max_duration: 30 # aligned with nemo/prepare_nemo_dataset.py defaults
    min_duration: 0.5

    # tarred datasets
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048

    # bucketing params
    bucketing_strategy: "synced_randomized"
    bucketing_batch_size: null

    # -------------------------------
    # Waveform-level data augmentation
    # -------------------------------
    # Applied online during training only.
    # Each augmentation is applied with prob p, independently per sample load.
    augmentor:
      # Pitch/rate change (resampling; changes pitch)
      speed:
        prob: 0.30
        sr: ${model.sample_rate}
        resample_type: kaiser_fast
        min_speed_rate: 0.90
        max_speed_rate: 1.10
        num_rates: 5

      # Codec/telephone-style distortion (requires sox available in environment)
      transcode_aug:
        prob: 0.1

      # Random gain (loudness)
      gain:
        prob: 0.20
        min_gain_dbfs: -10
        max_gain_dbfs: 10

      # Small time shift
      shift:
        prob: 0.15
        min_shift_ms: -5.0
        max_shift_ms: 5.0

      # Simple additive noise
      white_noise:
        prob: 0.20
        min_level: -50
        max_level: -10

      # Real-world noise samples (prepared via nemo/prepare_noise.py)
      noise:
        prob: 0.25
        manifest_path: ./output/noise_hf/noise_manifest.json
        min_snr_db: 5
        max_snr_db: 30

  validation_ds:
    manifest_filepath: ./output/eval_manifest.jsonl
    sample_rate: ${model.sample_rate}
    batch_size: 16
    shuffle: false
    use_start_end_token: false
    num_workers: 8
    pin_memory: true

  # test_ds: Uncomment and set manifest_filepath to run evaluation after training
  # test_ds:
  #   manifest_filepath: ./output/test_manifest.jsonl
  #   sample_rate: ${model.sample_rate}
  #   batch_size: 16
  #   shuffle: false
  #   use_start_end_token: false
  #   num_workers: 8
  #   pin_memory: true

  # You may find more detail on how to train a tokenizer at:
  # /scripts/tokenizers/process_asr_text_tokenizer.py
  # We recommend to use vocab size of 1024 with SPE Unigram for most languages
  tokenizer:
    dir: ./output/tokenizer_spe_bpe_v2048
    type: bpe # bpe (SentencePiece) or wpe (WordPiece)

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    sample_rate: ${model.sample_rate}
    normalize: "per_feature"
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    features: 128
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001
    pad_to: 0

  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2 # set to zero to disable it
    time_masks: 10 # set to zero to disable it
    freq_width: 27
    time_width: 0.05

  encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    feat_in: ${model.preprocessor.features}
    feat_out: -1
    n_layers: 17
    d_model: 512

    # Sub-sampling parameters
    subsampling: dw_striding
    subsampling_factor: 8
    subsampling_conv_channels: 256
    causal_downsampling: false

    # Reduction parameters
    reduction: null
    reduction_position: null
    reduction_factor: 1

    # Feed forward module
    ff_expansion_factor: 4

    # Multi-headed attention module
    self_attention_model: rel_pos
    n_heads: 8
    att_context_size: [-1, -1]
    att_context_style: regular
    xscaling: true
    untie_biases: true
    pos_emb_max_len: 5000

    # Convolution module
    conv_kernel_size: 9
    conv_norm_type: "batch_norm"
    conv_context_size: null

    # regularization
    dropout: 0.1
    dropout_pre_encoder: 0.1
    dropout_emb: 0.0
    dropout_att: 0.1

    stochastic_depth_drop_prob: 0.0
    stochastic_depth_mode: linear
    stochastic_depth_start_layer: 1

  decoder:
    _target_: nemo.collections.asr.modules.RNNTDecoder
    normalization_mode: null
    random_state_sampling: false
    blank_as_pad: true
    prednet:
      pred_hidden: ${model.model_defaults.pred_hidden}
      pred_rnn_layers: 1
      t_max: null
      dropout: 0.2

  joint:
    _target_: nemo.collections.asr.modules.RNNTJoint
    log_softmax: null
    preserve_memory: false
    fuse_loss_wer: true
    fused_batch_size: 4
    jointnet:
      joint_hidden: ${model.model_defaults.joint_hidden}
      activation: "relu"
      dropout: 0.2
      num_extra_outputs: ${model.model_defaults.num_tdt_durations}

  decoding:
    strategy: "greedy_batch"
    model_type: "tdt"
    durations: ${model.model_defaults.tdt_durations}
    greedy:
      max_symbols: 10
      use_cuda_graph_decoder: false # Disable CUDA graphs for Blackwell GPU compatibility
    beam:
      beam_size: 2
      return_best_hypothesis: False
      score_norm: true
    tsd_max_sym_exp: 50
    alsd_max_target_len: 2.0

  aux_ctc:
    ctc_loss_weight: 0.3
    use_cer: false
    ctc_reduction: "mean_batch"
    decoder:
      _target_: nemo.collections.asr.modules.ConvASRDecoder
      feat_in: null
      num_classes: -1
      vocabulary: []
    decoding:
      strategy: "greedy"
    interctc:
      loss_weights: []
      apply_at_layers: []

  loss:
    loss_name: "tdt"
    tdt_kwargs:
      fastemit_lambda: 0.0
      clamp: -1.0
      durations: ${model.model_defaults.tdt_durations}
      sigma: 0.02
      omega: 0.1

  optim:
    name: adamw
    lr: 5.0
    betas: [0.9, 0.98]
    weight_decay: 1e-3
    sched:
      name: NoamAnnealing
      d_model: ${model.encoder.d_model}
      warmup_steps: 10000
      warmup_ratio: null
      min_lr: 1e-6

trainer:
  devices: -1 # Use single GPU to avoid DDP initialization issues; set to -1 for multi-GPU
  num_nodes: 1
  max_epochs: 500
  max_steps: -1
  val_check_interval: 1.0
  accelerator: gpu
  strategy: auto # Let PyTorch Lightning choose the best strategy
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  precision: 32
  log_every_n_steps: 10
  enable_progress_bar: True
  num_sanity_val_steps: 2 # Run sanity check to catch data issues early
  check_val_every_n_epoch: 1
  sync_batchnorm: false # Disable when using single GPU
  enable_checkpointing: False
  logger: false
  benchmark: false

exp_manager:
  exp_dir: /workspace/nemo-training
  name: ${name}
  create_tensorboard_logger: false
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: "val_wer"
    mode: "min"
    save_top_k: 8
    always_save_nemo: True
  resume_from_checkpoint: null
  resume_if_exists: false
  resume_ignore_no_checkpoint: false
  create_wandb_logger: true
  wandb_logger_kwargs:
    name: ${name}
    project: "parakeet-nemo-asr"
    entity: null # set your wandb team/username if needed
    tags: ["fastconformer", "hybrid", "tdt-ctc"]
    log_model: false # set to true to log model checkpoints to wandb

# Keep the current working directory stable (Hydra otherwise runs inside a generated output dir,
# which breaks relative paths like `./output/train_manifest.jsonl`).
hydra:
  job:
    chdir: false
