compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_clipping: 1.0
  bf16:
    enabled: true
  zero_optimization:
    stage: 2
    overlap_comm: true
    reduce_scatter: true
    allgather_partitions: true
    contiguous_gradients: true
    offload_optimizer:
      device: none
    offload_param:
      device: none
distributed_type: DEEPSPEED
downcast_bf16: "no"
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
